const Words = [['imán','martillo','veneno','diario'],
['famoso','arcoiris','mafia','laberinto'],
['payaso','cohete','poker','elefante'],
['policía','arma','cadena','escorpión'],
['cadáver','ratón','ave','locomotora'],
['memoria','agua','velocidad','asesino'],
['accidente','matemáticas','religión','jirafa'],
['campana','cámara','libro de comics','bocina'],
['pista','calabozo','rana','perfume'],
['soborno','matadero','energía','fin de semana'],
['medalla','poema','mercado','boda'],
['laboratorio','mensaje','cuero','brújula'],
['heladera','candado','australia','traje'],
['nafta','sábana','ciencia','torre'],
['araña','ascensor','acuario','paraíso'],
['bote','amarillo','espanta pájaros','cerveza'],
['maní','museo','dormir','bicicleta'],
['tinta','fantasma','pulpo','pegamento'],
['ópera','hockey','ventana','ala'],
['jungla','montaña','verde','blanco'],
['senado','cabeza','hongo','bigote'],
['protesta','cuerpo','músico','metal'],
['artes marciales','clima','zapato','cocktail'],
['sangre','secretaria','escudo','muñeca'],
['collar','perla','negro','trigo'],
['noche','golf','teatro','psicólogo'],
['canon','enano','ballena','piloto'],
['china','oficina','festival','aguja'],
['camaleón','foto','elección','teléfono'],
['relok','cuchillo','estacionamiento','violeta'],
['mano','redes sociales','cuadrado','espacio exterior'],
['nacimiento','libro','rata','arqueología'],
['maestra','microscopio','búho','filosofía'],
['eucalipto','pantalones','corbata','elfo'],
['camino','ardilla','leyenda','geek'],
['escultura','beisbol','exorcismo','tambor'],
['alegría','antiguedad','café','cañon'],
['torta','calendario','espejo','caramelo'],
['manteca','patata','robo','teclado'],
['piano','bruja','chocolate','oveja'],
['cueva','perro','apocalipsis','pirata'],
['jaula','lagartija','puerta','extraterreste'],
['calor','casino','mariposa','computadora'],
['naturaleza','biología','sombrero','tortuga'],
['helicóptero','marioneta','océano','plaga'],
['canción','caballo','egipto','esqueleto'],
['submarino','olimpíadas','cíclope','cocina'],
['abejas','subte','trompeta','bosque'],
['cielo','tradición','revolución','química'],
['pintura','carnada','francia','escalera'],
['enojo','ambulancia','polvo','lapiz'],
['arpón','primavera','fuego','dinosaurio'],
['espada','droga','laser','planeta tierra'],
['concurso','atleta','magia','doctor'],
['invierno','botella','bebé','mañana'],
['cuartel','cable','orquesta','comunismo'],
['monje','botón','punk','construcción'],
['tiempo','ciencia ficción','escuela','círculo'],
['nariz','television','pesadilla','llave'],
['gigante','grito','corrupción','satélite'],
['madre','frut','vaso','caza'],
['manzana','receta','estrés','diente'],
['pierna','valija','nieve','renacimiento'],
['juego','zanahoria','pescado','ropa interior'],
['avión','pizza','circo','cerdo'],
['índice','texas','bandera','misterio'],
['lluvia','queso','saxofón','ejército'],
['estómago','sandwich','algodón','tormenta eléctrica'],
['trabajo','monumento','baño','monstruo'],
['bolsillo','armadura','biblioteca','huevo'],
['dragón','pegaso','isla','rio de janeiro'],
['rompecabezas','alemania','lamparita','rey'],
['lenguaje','unicornio','ártico','electricidad'],
['anillo','dios','cine','padre'],
['diamante','pileta','alcohol','ataque'],
['pie','pozo','arte','hospital'],
['mujer','río','luna','jardín'],
['nido','jabón','pared','picnic'],
['paracaídas','baile','verano','vela'],
['galletita','princesa','guillotina','sueño'],
['vestido','lobo','diccionario','volcán'],
['concierto','locura','triángulo','mesa'],
['orgo','brazo','amor','hotel'],
['capitalismo','postre','violín','pan'],
['cirugía','rojo','habitación','prehistoria'],
['barba','naranja','fraude','guitarra'],
['azul','edad media','vacaciones','piel'],
['oreja','pavo real','horror','pedazo'],
['gusto','economía','trineo','atardecer'],
['vampiro','almuerzo','pirámide','dominó'],
['espía','enfermedad','banco','mayordomo'],
['serpiente','duende','sótano','oasis'],
['infancia','santuario','desayuno','buzo'],
['salida','zoológico','jazz','león'],
['cama','lengua','regalo','silla'],
['detective','auto','capa','muerte'],
['bomba','cara','banana','genio'],
['pluma','gaucho','flecha','contaminación'],
['nube','pasajero','ladrillo','máscara'],
['cena','reloj de arena','nueva york','miel'],
['gato','techo','cucaracha','alfombra'],
['rusia','tristeza','arquitectura','planeta'],
['california','robot','torpedo','lana'],
['clon','frontera','plomero','centauro'],
['aristócrata','dinero','pingüino','otoño'],
['zombi','playa','iglesia','máquina'],
['corona','diablo','plástico','áfrica'],
['cartón','sirena','risa','fútbol'],
['hombre','raíz','horno','guerra'],
['turista','restaurante','internet','cumpleaños']];
